.TH "stcollectd" 1
.SH NAME
stcollectd \- sFlow collector daemon
.SH SYNOPSIS
.B stcollectd
[options]
.SH DESCRIPTION
This daemon collects sFlow samples
.SH OPTIONS
.TP
.B \-d
Do not daemonize, but keep the daemon running in the foreground, log messages
will be written both to the system log and to stdout
.TP
.B \-v
Print info messages
.TP
.B \-vv
Print both info and debug messages
.TP
.B \-x
Print out information about each sample as it is parsed, used to debug the parsing processs.
.TP
.B \-X
Print out the samples in HEX for debugging purposes.
This is not advised under high sampling rates as it will generate a huge amount of output
.TP
.B \-h
Show the help
.SH "SEE ALSO"
stprocessd(1) sflow-toolkit.conf(5)
.SH BUGS
None
