.TH "stconvert" 1
.SH NAME
stconvert \- extract and convert collected sFlow data to various file formats
.SH SYNOPSIS
.B stconvert
[-p] -i <filename> -o <filename>
.SH DESCRIPTION
extract and convert collected sFlow data to various file formats
.SH OPTIONS
.TP
.B \-h
Show usage information
.TP
.B \-i <filename>
Set input file (collected sFlow data)
.TP
.B \-o <filename>
Set output filename
.TP
.B \-p
Output pcap format
.SH "SEE ALSO"
stcollectd(1)
.SH BUGS
None
