#!/bin/bash

# The directory where the output images should be put
DIR=/netsw/sflow

# The full path to the rrdtool executable
RRDTOOL=/usr/bin/rrdtool

# The full path to the database
DB_STCOLLECTD=$DIR/statistics_stcollectd.rrd
DB_STPROCESSD=$DIR/statistics_stprocessd.rrd

FULL=775
HALF=337

COLOR1=#FF0000
COLOR2=#00FF00
COLOR3=#0000FF
COLOR4=#FF00FF

### CHANGES ABOVE THIS LINE ###

$RRDTOOL graph $DIR/statistics/samples_1h.png \
	-h 150 -w $FULL	\
	--vertical-label "samples/sec" \
	--title "Sampling rate" \
	--start end-1h \
	DEF:samples=$DB_STCOLLECTD:samples:AVERAGE \
	CDEF:samples_2=samples,0,GT,samples,1000000,LT,samples,UNKN,IF,UNKN,IF \
	LINE1:samples_2$COLOR1:"Samples" \
	DEF:datagrams=$DB_STCOLLECTD:datagrams:AVERAGE \
	CDEF:datagrams_2=samples,0,GT,datagrams,1000000,LT,datagrams,UNKN,IF,UNKN,IF \
	LINE1:datagrams_2$COLOR2:"Datagrams" \
	DEF:samples_flow=$DB_STCOLLECTD:samples_flow:AVERAGE \
	CDEF:samples_flow_2=samples_flow,0,GT,samples_flow,1000000,LT,samples_flow,UNKN,IF,UNKN,IF \
	LINE1:samples_flow_2$COLOR3:"Flow Samples" \
	DEF:samples_cntr=$DB_STCOLLECTD:samples_cntr:AVERAGE \
	CDEF:samples_cntr_2=samples_cntr,0,GT,samples_cntr,1000000,LT,samples_cntr,UNKN,IF,UNKN,IF \
	LINE1:samples_cntr_2$COLOR4:"Counter Samples"	

$RRDTOOL graph $DIR/statistics/samples_6h.png \
	-h 100 -w $FULL	\
	--vertical-label "samples/sec" \
	--title "Sampling rate" \
	--start end-6h \
	DEF:samples=$DB_STCOLLECTD:samples:AVERAGE \
	CDEF:samples_2=samples,0,GT,samples,1000000,LT,samples,UNKN,IF,UNKN,IF \
	LINE1:samples_2$COLOR1:"Samples" \
	DEF:datagrams=$DB_STCOLLECTD:datagrams:AVERAGE \
	CDEF:datagrams_2=samples,0,GT,datagrams,1000000,LT,datagrams,UNKN,IF,UNKN,IF \
	LINE1:datagrams_2$COLOR2:"Datagrams" \
	DEF:samples_flow=$DB_STCOLLECTD:samples_flow:AVERAGE \
	CDEF:samples_flow_2=samples_flow,0,GT,samples_flow,1000000,LT,samples_flow,UNKN,IF,UNKN,IF \
	LINE1:samples_flow_2$COLOR3:"Flow Samples" \
	DEF:samples_cntr=$DB_STCOLLECTD:samples_cntr:AVERAGE \
	CDEF:samples_cntr_2=samples_cntr,0,GT,samples_cntr,1000000,LT,samples_cntr,UNKN,IF,UNKN,IF \
	LINE1:samples_cntr_2$COLOR4:"Counter Samples"	

$RRDTOOL graph $DIR/statistics/samples_24h.png \
	-h 100 -w $FULL	\
	--vertical-label "samples/sec" \
	--title "Sampling rate" \
	--start end-6h \
	DEF:samples=$DB_STCOLLECTD:samples:AVERAGE \
	CDEF:samples_2=samples,0,GT,samples,1000000,LT,samples,UNKN,IF,UNKN,IF \
	LINE1:samples_2$COLOR1:"Samples" \
	DEF:datagrams=$DB_STCOLLECTD:datagrams:AVERAGE \
	CDEF:datagrams_2=samples,0,GT,datagrams,1000000,LT,datagrams,UNKN,IF,UNKN,IF \
	LINE1:datagrams_2$COLOR2:"Datagrams" \
	DEF:samples_flow=$DB_STCOLLECTD:samples_flow:AVERAGE \
	CDEF:samples_flow_2=samples_flow,0,GT,samples_flow,1000000,LT,samples_flow,UNKN,IF,UNKN,IF \
	LINE1:samples_flow_2$COLOR3:"Flow Samples" \
	DEF:samples_cntr=$DB_STCOLLECTD:samples_cntr:AVERAGE \
	CDEF:samples_cntr_2=samples_cntr,0,GT,samples_cntr,1000000,LT,samples_cntr,UNKN,IF,UNKN,IF \
	LINE1:samples_cntr_2$COLOR4:"Counter Samples"	

$RRDTOOL graph $DIR/statistics/samples_1w.png \
	-h 50 -w $HALF	\
	--vertical-label "samples/sec" \
	--title "Sampling rate" \
	--start end-1w \
	DEF:samples=$DB_STCOLLECTD:samples:AVERAGE \
	CDEF:samples_2=samples,0,GT,samples,1000000,LT,samples,UNKN,IF,UNKN,IF \
	LINE1:samples_2$COLOR1:"Samples" \
	DEF:datagrams=$DB_STCOLLECTD:datagrams:AVERAGE \
	CDEF:datagrams_2=samples,0,GT,datagrams,1000000,LT,datagrams,UNKN,IF,UNKN,IF \
	LINE1:datagrams_2$COLOR2:"Datagrams" \
	DEF:samples_flow=$DB_STCOLLECTD:samples_flow:AVERAGE \
	CDEF:samples_flow_2=samples_flow,0,GT,samples_flow,1000000,LT,samples_flow,UNKN,IF,UNKN,IF \
	LINE1:samples_flow_2$COLOR3:"Flow Samples" \
	DEF:samples_cntr=$DB_STCOLLECTD:samples_cntr:AVERAGE \
	CDEF:samples_cntr_2=samples_cntr,0,GT,samples_cntr,1000000,LT,samples_cntr,UNKN,IF,UNKN,IF \
	LINE1:samples_cntr_2$COLOR4:"Counter Samples"	

$RRDTOOL graph $DIR/statistics/samples_1m.png \
	-h 50 -w $HALF	\
	--vertical-label "samples/sec" \
	--title "Sampling rate" \
	--start end-1m \
	DEF:samples=$DB_STCOLLECTD:samples:AVERAGE \
	CDEF:samples_2=samples,0,GT,samples,1000000,LT,samples,UNKN,IF,UNKN,IF \
	LINE1:samples_2$COLOR1:"Samples" \
	DEF:datagrams=$DB_STCOLLECTD:datagrams:AVERAGE \
	CDEF:datagrams_2=samples,0,GT,datagrams,1000000,LT,datagrams,UNKN,IF,UNKN,IF \
	LINE1:datagrams_2$COLOR2:"Datagrams" \
	DEF:samples_flow=$DB_STCOLLECTD:samples_flow:AVERAGE \
	CDEF:samples_flow_2=samples_flow,0,GT,samples_flow,1000000,LT,samples_flow,UNKN,IF,UNKN,IF \
	LINE1:samples_flow_2$COLOR3:"Flow Samples" \
	DEF:samples_cntr=$DB_STCOLLECTD:samples_cntr:AVERAGE \
	CDEF:samples_cntr_2=samples_cntr,0,GT,samples_cntr,1000000,LT,samples_cntr,UNKN,IF,UNKN,IF \
	LINE1:samples_cntr_2$COLOR4:"Counter Samples"	

#### System information - CPU ###

$RRDTOOL graph $DIR/statistics/cpu_1h.png \
	-h 80 -w $FULL \
	--upper-limit 100 \
	--lower-limit 0	\
	--title "CPU (%)" \
	--start end-1h \
	--vertical-label "usage (%)" \
        DEF:cpu_stcollectd=$DB_STCOLLECTD:cpu:AVERAGE LINE1:cpu_stcollectd$COLOR1:"stcollectd" \
        DEF:cpu_stprocessd=$DB_STPROCESSD:cpu:AVERAGE LINE1:cpu_stprocessd$COLOR2:"stprocessd"

$RRDTOOL graph $DIR/statistics/cpu_6h.png \
	-h 80 -w $FULL \
	--upper-limit 100 \
	--lower-limit 0	\
	--title "CPU (%)" \
	--start end-6h \
	--vertical-label "usage (%)" \
        DEF:cpu_stcollectd=$DB_STCOLLECTD:cpu:AVERAGE LINE1:cpu_stcollectd$COLOR1:"stcollectd" \
        DEF:cpu_stprocessd=$DB_STPROCESSD:cpu:AVERAGE LINE1:cpu_stprocessd$COLOR2:"stprocessd"

$RRDTOOL graph $DIR/statistics/cpu_24h.png \
	-h 80 -w $FULL \
	--upper-limit 100 \
	--lower-limit 0	\
	--title "CPU (%)" \
	--start end-24h \
	--vertical-label "usage (%)" \
        DEF:cpu_stcollectd=$DB_STCOLLECTD:cpu:AVERAGE LINE1:cpu_stcollectd$COLOR1:"stcollectd" \
        DEF:cpu_stprocessd=$DB_STPROCESSD:cpu:AVERAGE LINE1:cpu_stprocessd$COLOR2:"stprocessd"

#### System information - Memory ###

$RRDTOOL graph $DIR/statistics/mem_1h.png \
	-h 80 -w $FULL \
	--title "Virtual memory" \
	--start end-1h \
	--vertical-label "VMEM (MB)" \
        DEF:mem_stcollectd=$DB_STCOLLECTD:mem:AVERAGE \
	CDEF:mem_stcollectd_2=mem_stcollectd,1000,\* \
	LINE1:mem_stcollectd_2$COLOR1:"stcollectd" \
        DEF:mem_stprocessd=$DB_STPROCESSD:mem:AVERAGE \
	CDEF:mem_stprocessd_2=mem_stprocessd,1000,\* \
	LINE1:mem_stprocessd_2$COLOR2:"stprocessd" 

$RRDTOOL graph $DIR/statistics/mem_6h.png \
	-h 80 -w $FULL \
	--title "Virtual memory" \
	--start end-6h \
	--vertical-label "VMEM (MB)" \
        DEF:mem_stcollectd=$DB_STCOLLECTD:mem:AVERAGE \
	CDEF:mem_stcollectd_2=mem_stcollectd,1000,\* \
	LINE1:mem_stcollectd_2$COLOR1:"stcollectd" \
        DEF:mem_stprocessd=$DB_STPROCESSD:mem:AVERAGE \
	CDEF:mem_stprocessd_2=mem_stprocessd,1000,\* \
	LINE1:mem_stprocessd_2$COLOR2:"stprocessd" 

$RRDTOOL graph $DIR/statistics/mem_24h.png \
	-h 80 -w $FULL \
	--title "Virtual memory" \
	--start end-24h \
	--vertical-label "VMEM (MB)" \
        DEF:mem_stcollectd=$DB_STCOLLECTD:mem:AVERAGE \
	CDEF:mem_stcollectd_2=mem_stcollectd,1000,\* \
	LINE1:mem_stcollectd_2$COLOR1:"stcollectd" \
        DEF:mem_stprocessd=$DB_STPROCESSD:mem:AVERAGE \
	CDEF:mem_stprocessd_2=mem_stprocessd,1000,\* \
	LINE1:mem_stprocessd_2$COLOR2:"stprocessd" 

#### System information - Disk ###

$RRDTOOL graph $DIR/statistics/write_1h.png \
	-h 80 -w $FULL \
	--title "Bytes written" \
	--start end-1h \
	--vertical-label "Bytes" \
        DEF:write_stcollectd=$DB_STCOLLECTD:write:AVERAGE \
	CDEF:write_stcollectd_2=write_stcollectd,0,GT,write_stcollectd,1000000,LT,write_stcollectd,UNKN,IF,UNKN,IF \
	LINE1:write_stcollectd_2$COLOR1

$RRDTOOL graph $DIR/statistics/write_6h.png \
	-h 80 -w $FULL \
	--title "Bytes written" \
	--start end-6h \
	--vertical-label "Bytes" \
        DEF:write_stcollectd=$DB_STCOLLECTD:write:AVERAGE \
	CDEF:write_stcollectd_2=write_stcollectd,0,GT,write_stcollectd,1000000,LT,write_stcollectd,UNKN,IF,UNKN,IF \
	LINE1:write_stcollectd_2$COLOR1

$RRDTOOL graph $DIR/statistics/write_24h.png \
	-h 80 -w $FULL \
	--title "Bytes written" \
	--start end-24h \
	--vertical-label "Bytes" \
        DEF:write_stcollectd=$DB_STCOLLECTD:write:AVERAGE \
	CDEF:write_stcollectd_2=write_stcollectd,0,GT,write_stcollectd,1000000,LT,write_stcollectd,UNKN,IF,UNKN,IF \
	LINE1:write_stcollectd_2$COLOR1

#### Misc stats

$RRDTOOL graph $DIR/statistics/agents_1h.png \
	-h 50 -w $HALF \
	--title "Active agents" \
	--start end-1h \
        DEF:agents_stcollectd=$DB_STCOLLECTD:agents:AVERAGE LINE1:agents_stcollectd$COLOR1

$RRDTOOL graph $DIR/statistics/agents_6h.png \
	-h 50 -w $HALF \
	--title "Active agents" \
	--start end-6h \
        DEF:agents_stcollectd=$DB_STCOLLECTD:agents:AVERAGE LINE1:agents_stcollectd$COLOR1

$RRDTOOL graph $DIR/statistics/agents_24h.png \
	-h 50 -w $HALF \
	--title "Active agents" \
	--start end-24h \
        DEF:agents_stcollectd=$DB_STCOLLECTD:agents:AVERAGE LINE1:agents_stcollectd$COLOR1

$RRDTOOL graph $DIR/statistics/messages_1h.png \
	-h 50 -w $HALF \
	--title "Messages pending" \
	--start end-1h \
        DEF:messages_stprocessd=$DB_STPROCESSD:messages:AVERAGE LINE1:messages_stprocessd$COLOR1

$RRDTOOL graph $DIR/statistics/messages_6h.png \
	-h 50 -w $HALF \
	--title "Messages pending" \
	--start end-6h \
        DEF:messages_stprocessd=$DB_STPROCESSD:messages:AVERAGE LINE1:messages_stprocessd$COLOR1

$RRDTOOL graph $DIR/statistics/messages_24h.png \
	-h 50 -w $HALF \
	--title "Messages pending" \
	--start end-24h \
        DEF:messages_stprocessd=$DB_STPROCESSD:messages:AVERAGE LINE1:messages_stprocessd$COLOR1
